package com.example.todoapp.fragments.util

object Const {
    const val NEW_ID = "NEW_ID"
    const val NEW_TEXT = "NEW_TEXT"
    const val NEW_IMPORTANCE = "NEW_IMPORTANCE"
    const val NEW_DEADLINE = "NEW_DEADLINE"
    const val NEW_DATE_OF_CHANGES = "NEW_DATE_OF_CHANGES"
    const val NEW = "NEW"
    const val CHANGE = "CHANGE"
    const val ID = "ID"
    const val TEXT = "TEXT"
    const val IMPORTANCE = "IMPORTANCE"
    const val DEADLINE = "DEADLINE"
    const val DELETE = "DELETE"
    const val DELETE_BY_ID = "DELETE_BY_ID"
    const val VISIBLE = "VISIBLE"
    const val ERROR_404 = 404
    const val ERROR_400 = 400
    const val ZERO = "0"
    const val URL_API ="https://beta.mrdekk.ru/todobackend/"
    const val PATTERN = "d MMMM yyyy 'г.'"
    const val RU = "ru"
    const val AUTHORIZATION = "Authorization: Bearer chubascos"
    const val LIST = "list"
    const val LIST_ID = "list/{id}"
    const val LAST_KNOWN_REVISION = "X-Last-Known-Revision"
    const val SMALL_ID = "id"
    const val SMALL_TEXT = "text"
    const val SMALL_IMPORTANCE = "importance"
    const val SMALL_DEADLINE = "deadline"
    const val SMALL_DONE = "done"
    const val SMALL_CREATED_AT = "created_at"
    const val SMALL_CHANGED_AT = "changed_at"
    const val SMALL_LAST_UPDATED_BY = "last_updated_by"
    const val REVISION = "revision"
    const val ELEMENT = "element"
    const val DATABASE_NAME = "todoItem-database"
    const val TODO_ITEM = "todo_item"
    const val TIMEOUT = 10000L
    const val BACKGROUND_WORKER = "BackgroundWorker"
}